name: Fix Vulnerabilities

on:
  schedule:
    - cron: '0 9 * * 1-5'
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch on which to fix vulnerabilities"
        required: true
        type: string

jobs:
  fix-vulnerabilities:
    uses: giantswarm/github-workflows/.github/workflows/shared.fix-vulnerabilities.yaml@reusable-workflows
    with:
      branch: ${{ github.event.inputs.branch || github.ref_name }}
    secrets:
      # forward whatever your template needs:
      GITHUB_TOKEN:     ${{ secrets.GITHUB_TOKEN }}
      HERALD_APP_ID:    ${{ secrets.HERALD_APP_ID }}
      HERALD_APP_KEY:   ${{ secrets.HERALD_APP_KEY }}
