name: Scorecard supply-chain security

on:
  # For Branch-Protection check. Only the default branch is supported. See
  # https://github.com/ossf/scorecard/blob/main/docs/checks.md#branch-protection
  branch_protection_rule:
  # To guarantee Maintained check is occasionally updated. See
  # https://github.com/ossf/scorecard/blob/main/docs/checks.md#maintained
  schedule:
    - cron: '15 15 15 * *'
  push:
    branches:
      - main
      - master
  workflow_dispatch: {}

jobs:
  call-scorecard:
    uses: giantswarm/github-workflows/.github/workflows/shared.run-ossf-scorecard.yaml@main
    # no inputs or extra secrets needed
