name: Create Release

on:
  push:
    branches:
      - 'legacy'
      - 'main'
      - 'master'
      - 'release-v*.*.x'
      # "!" negates previous positive patterns so it has to be at the end.
      - '!release-v*.x.x'

jobs:
  call-create-release:
    uses: giantswarm/github-workflows/.github/workflows/shared.create-release.yaml@main
    secrets:
      TAYLORBOT_GITHUB_ACTION:           ${{ secrets.TAYLORBOT_GITHUB_ACTION }}
