name: Add Issue to Project when assigned

on:
  issues:
    types:
    - assigned
    - labeled

jobs:
  call-add-issue-to-project:
    uses: giantswarm/github-workflows/.github/workflows/shared.add-issue-to-project-template.yml@reusable-workflows
    secrets:
      ISSUE_AUTOMATION: ${{ secrets.ISSUE_AUTOMATION }}
