name: Add appropriate labels to issue

on:
  issues:
    types: [assigned]

jobs:
  call-add-issue-label:
    uses: giantswarm/github/.github/workflows/shared-add-issue-label-template.yml@reusable-workflows
    secrets:
      ISSUE_AUTOMATION: ${{ secrets.ISSUE_AUTOMATION }}
