name: Add appropriate labels to issue

on:
  issues:
    types: [assigned]

jobs:
  call-add-issue-label:
    uses: giantswarm/github-workflows/.github/workflows/shared.add-team-labels.yaml@main
    secrets:
      ISSUE_AUTOMATION: ${{ secrets.ISSUE_AUTOMATION }}
